# Generated by Django 4.2.11 on 2026-03-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor_found',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
