# Generated by Django 4.2.11 on 2026-03-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_tutor_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='student_found',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
