# Generated by Django 4.2.9 on 2026-04-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_qrscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QRScan',
        ),
    ]
